INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (1, 'AW', 'Aruba', '阿鲁巴');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (10, 'CU', 'Cuba', '古巴');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (100, 'RW', 'Rwanda', '卢旺达');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (102, 'AT', 'Austria', '奥地利');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (104, 'MV', 'Maldives', '马尔代夫');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (105, 'MT', 'Malta', '马耳他');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (106, 'MY', 'Malaysia', '马来西亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (107, 'MW', 'Malawi', '马拉维');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (108, 'ML', 'Mali', '马里');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (11, 'OM', 'Oman', '阿曼');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (110, 'MU', 'Mauritius', '毛里求斯');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (111, 'MK', 'Macedonia', '马其顿');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (112, 'MO', 'Macao  China', '中国澳门');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (113, 'MQ', 'Martinique', '马提尼克');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (114, 'YT', 'Territorial Collecti', '法属马约特岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (115, 'US', 'America', '美国');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (117, 'MN', 'Mongolia', '蒙古');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (118, 'BD', 'Bengal', '孟加拉国');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (121, 'MM', 'Burma', '缅甸');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (123, 'PE', 'Peru', '秘鲁');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (124, 'DM', 'The Commonwealth of ', '多米尼克');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (125, 'MD', 'Moldova', '摩尔多瓦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (126, 'MA', 'Morocco', '摩洛哥');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (127, 'MC', 'Monaco', '摩纳哥');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (128, 'MZ', 'Mozambique', '莫桑比克');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (13, 'GY', 'Guyana', '圭亚那');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (130, 'AZ', 'Azerbaijan', '阿塞拜疆');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (131, 'MX', 'Mexico', '墨西哥');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (133, 'NA', 'Namibia', '纳米比亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (135, 'ZA', 'South Africa', '南非');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (140, 'BB', 'Barbados', '巴巴多斯');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (143, 'NP', 'Nepal', '尼泊尔');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (144, 'NI', 'Nicaragua', '尼加拉瓜');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (147, 'NE', 'Niger', '尼日尔');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (148, 'NG', 'Nigeria', '尼日利亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (150, 'NO', 'Norway', '挪威');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (152, 'PW', 'The Republic of Pala', '帕劳');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (154, 'PT', 'Portugal', '葡萄牙');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (160, 'BS', 'Bahamas', '巴哈马');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (163, 'JP', 'Japan', '日本');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (165, 'SE', 'Sweden', '瑞典');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (166, 'CH', 'Switzerland', '瑞士');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (167, 'SV', 'Salvador', '萨尔瓦多');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (168, 'RS', 'Serbia', '塞尔维亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (169, 'SL', 'Sierra Leone', '塞拉利昂');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (170, 'SN', 'Senegal', '塞内加尔');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (171, 'BY', 'Belarus', '白俄罗斯');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (172, 'CY', 'Cyprus', '塞浦路斯');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (173, 'SC', 'Seychelles', '塞舌尔');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (174, 'WS', 'Samoa', '萨摩亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (18, 'HT', 'Haiti', '海地');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (182, 'BM', 'Bermuda', '百慕大');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (185, 'SM', 'San Marino', '圣马力诺');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (190, 'LK', 'Sri Lanka', '斯里兰卡');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (191, 'PK', 'Pakistan', '巴基斯坦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (192, 'SK', 'Slovakia', '斯洛伐克');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (193, 'SZ', 'Swaziland', '斯威士兰');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (194, 'SD', 'Sudan', '苏丹');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (197, 'SR', 'Suriname', '苏里南');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2, 'GL', 'Greenland', '格陵兰岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (201, 'AF', 'Afghanistan', '阿富汗');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (202, 'PY', 'Paraguay', '巴拉圭');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (203, 'TH', 'Thailand', '泰国');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (205, 'TW', 'Taiwan  China', '中国台湾');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (209, 'TO', 'Tonga', '汤加');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (211, 'TZ', 'Tanzania', '坦桑尼亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (213, 'PS', 'Palestine', '巴勒斯坦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (216, 'TR', 'Turkey', '土耳其');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (217, 'TN', 'Tunis', '突尼斯');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (218, 'VU', 'Vanuatu', '瓦努阿图');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (219, 'GT', 'Guatemala', '危地马拉');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (22, 'AD', 'Andorra', '安道尔');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (223, 'VE', 'Venezuela', '委内瑞拉');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (224, 'BN', 'Brunei', '文莱');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (226, 'UG', 'Uganda', '乌干达');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (231, 'UA', 'Ukraine', '乌克兰');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (232, 'BH', 'Bahrain', '巴林');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (233, 'UY', 'Uruguay', '乌拉圭');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (24, 'KR', 'Korea', '韩国');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (240, 'HK', 'Hongkong China', '中国香港');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (241, 'PA', 'Panama', '巴拿马');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (242, 'ES', 'Spain', '西班牙');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (243, 'GR', 'Greece', '希腊');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (248, 'SG', 'Singapore', '新加坡');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (250, 'NZ', 'New Zealand', '新西兰');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (254, 'HU', 'Hungary', '匈牙利');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (255, 'WS', 'The Independent Stat', '西萨摩亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (259, 'SY', 'Syria', '叙利亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (261, 'JM', 'Jamaica', '牙买加');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (262, 'BG', 'Bulgaria', '保加利亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (263, 'AM', 'Armenia', '亚美尼亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (269, 'YE', 'Yemen', '也门');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2714, 'IC', 'Canary Islands', '加那利群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (272, 'IT', 'Italy', '意大利');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (274, 'IQ', 'Iraq', '伊拉克');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2747, 'VA', 'Vatican', '梵蒂冈');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (275, 'IR', 'Iran', '伊朗');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2750, 'FK', 'Islas Malvinas', '福克兰群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2751, 'TJ', 'Tajikistan', '塔吉克斯坦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2753, 'GQ', 'equatorial guinea', '赤道几内亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2754, 'VC', 'Saint Vincent and th', '圣文森特和格林纳丁斯');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2758, 'TC', 'The Turks and Caicos', '特克斯和凯科斯群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2759, 'SB', 'Solomon Islands', '所罗门群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2762, 'NC', 'New Caledonia', '新加勒多尼亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2763, 'EH', 'Western Sahara', '西撒哈拉');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2764, 'TM', 'Turkmenistan', '土库曼斯坦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2765, 'CV', 'The Republic of Cape', '佛得角');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2766, 'NR', 'The Republic of Naur', '瑙鲁共和国');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2767, 'MP', 'Saipan lsland', '塞班岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (277, 'IN', 'India', '印度');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2770, 'MS', 'Montserrat', '蒙特塞拉岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2771, 'NF', 'Norfolk Island', '诺福克岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2772, 'KS', 'Kosovo', '科索沃');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2776, 'CW', 'Curacao', '库拉索');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2777, 'GG', 'Guernsey', '根西岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2778, 'KN', 'The Federation of Sa', '圣基茨和尼维斯联邦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2779, 'MS', 'Montserrat', '蒙特塞拉特');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2780, 'CD', 'Democratic Republic ', '刚果(金)');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2781, 'CG', 'Congo', '刚果(布)');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2782, 'Z2', 'Ascension Island', '阿森松岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2783, 'TL', 'Democratic Republic ', '东帝汶');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2785, 'NU', 'Niue', '纽埃');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2786, 'PN', 'Pitcairn Islands', '皮特凯恩群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2787, 'CX', 'Christmas Island', '圣诞岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2788, 'ST', 'Sao Tome and Princip', '圣多美和普林西比');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2789, 'SH', 'Saint Helena', '圣赫勒拿');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (279, 'GB', 'Britain', '英国');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2790, 'TV', 'Tuvalu', '图瓦卢');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2791, 'TK', 'Tokelau', '托克劳');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2792, 'Z4', 'NULL', '伊夫尼');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2793, 'IM', 'Isle of Man, British', '马恩岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2795, 'MP', 'Mariana lslands', '马里亚纳群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (281, 'IL', 'Israel', '以色列');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2816, 'DO', 'DOMINICAN REPUBLIC', '多米尼加共和国');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (282, 'BR', 'Brazil', '巴西');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2826, 'GS', 'South Georgia and th', '南乔治亚岛和南桑威奇群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2828, 'IO', 'British Indian Ocean', '英属印度洋领地');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2834, 'UM', 'United States Minor ', '美国本土外小岛屿');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2840, 'SR', 'Serbia', '塞尔维亚-速卖通');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2841, 'YT', 'Mayotte', '马约特');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2842, 'MN', 'The Republic of Mont', '黑山-速卖通');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2844, 'UK', 'Britain', '英国-万邑通');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2849, 'BL', 'Saint Barthelemy', '圣巴泰勒米岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (285, 'JO', 'Jordan', '约旦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2850, 'AX', 'Aland Islands', '奥兰群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2851, 'SS', 'SOUTH SUDAN', '南苏丹共和国');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2852, 'TF', 'fashunanbulingdi', '法属南部领地');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2853, 'SJ', 'The Svalbard archipe', '斯瓦尔巴岛和扬马延岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2854, 'SX', 'St.Maarten', '荷属圣马丁');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2855, 'BQ', 'Bonaire', '博奈尔、圣尤斯特歇斯和萨巴');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2856, 'XZ', 'Zanzibar', '桑给巴尔');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2857, 'BV', 'Bouvet Island', '布维岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2858, 'CI', 'The Republic of Ivor', '象牙海岸');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (2859, 'AQ', 'Antarctica', '南极洲');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (286, 'VN', 'Vietnam', '越南');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (288, 'TD', 'Chad', '乍得');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (289, 'ZM', 'Zambia', '赞比亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (297, 'GI', 'Gibraltar', '直布罗陀');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (298, 'CL', 'Chile', '智利');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (299, 'CF', 'The Central African ', '中非');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (3, 'GE', 'Georgia', '格鲁吉亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (30, 'NL', 'Netherlands', '荷兰');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (303, 'AR', 'Argentina', '阿根廷');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (308, 'BJ', 'Benin', '贝宁');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (309, 'BE', 'Belgium', '比利时');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (310, 'IS', 'Iceland', '冰岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (311, 'BW', 'Botswana', '博茨瓦纳');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (312, 'PR', 'Porto Rico', '波多黎各');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (313, 'BA', 'Bosnia and Herzegovi', '波黑');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (314, 'PL', 'Poland', '波兰');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (315, 'IE', 'Ireland', '爱尔兰');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (316, 'BO', 'Bolivia', '玻利维亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (317, 'BZ', 'Belize', '伯利兹');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (318, 'BT', 'Bhutan', '不丹');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (319, 'BI', 'Burundi', '布隆迪');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (324, 'EG', 'Egypt', '埃及');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (326, 'KP', 'North Korea', '朝鲜');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (334, 'DK', 'Denmark', '丹麦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (338, 'DE', 'Germany', '德国');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (343, 'TT', 'Trinidad and Tobago', '特立尼达和多巴哥');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (344, 'TG', 'Togo', '多哥');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (345, 'EE', 'Estonia', '爱沙尼亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (346, 'DM', 'Dominica', '多米尼加岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (347, 'EC', 'Ecuador', '厄瓜多尔');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (348, 'RU', 'Russian', '俄罗斯');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (35, 'HN', 'Honduras', '洪都拉斯');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (350, 'FR', 'France', '法国');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (351, 'FO', 'The Faroe Islands', '法罗群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (352, 'FJ', 'Fiji', '斐济');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (353, 'PH', 'Philippines', '菲律宾');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (354, 'AE', 'United Arab Emirates', '阿联酋');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (356, 'FI', 'Finland', '芬兰');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (360, 'GM', 'Gambian', '冈比亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (363, 'AL', 'Albania', '阿尔巴尼亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (364, 'CR', 'Costarica', '哥斯达黎加');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (365, 'KZ', 'Kazakhstan', '哈萨克斯坦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (366, 'AN', 'Netherlands Antilles', '荷属安的列斯群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (367, 'KG', 'Kirghizia', '吉尔吉斯斯坦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (368, 'LI', 'Liechtenstein', '列支敦士登');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (369, 'MG', 'Madagascar', '马达加斯加');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (370, 'DZ', 'Algeria', '阿尔及利亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (371, 'MR', 'Mauritania', '毛里塔尼亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (372, 'MH', 'Marshall Island', '马绍尔群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (373, 'AS', 'Amercian Samoa', '美属萨摩亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (374, 'VI', 'The United States Vi', '美属维尔京群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (375, 'FM', 'Micronesia', '密克罗尼西亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (376, 'PG', 'Papua New Guinea', '巴布亚新几内亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (377, 'SA', 'Saudi Arabia', '沙特阿拉伯');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (378, 'PM', 'Saint Pierre and Miq', '圣皮埃尔和密克隆');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (379, 'SI', 'Slovenia', '斯洛文尼亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (382, 'UZ', 'Uzbekistan', '乌兹别克斯坦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (383, 'NC', 'New Caledonia', '新喀里多尼亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (384, 'ID', 'Indonesia', '印度尼西亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (385, 'VG', 'THE BRITISH VRIGIN I', '英属维尔京');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (387, 'PF', 'Polynesia', '波利尼西亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (388, 'BF', 'Burkina Faso', '布基纳法索');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (389, 'ET', 'Ethiopia', '埃塞俄比亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (390, 'PF', 'FRENCH POLYNESIA', '法属波利尼西亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (391, 'GF', 'Guyane Francaise', '法属圭亚那');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (395, 'KI', 'Kiribati', '基里巴斯');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (397, 'SO', 'Somali', '索马里');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (398, 'ER', 'Eritrea', '厄立特里亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (4, 'CO', 'Colombia', '哥伦比亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (40, 'AO', 'Angola', '安哥拉');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (400, 'GD', 'Grenada', '格林纳达');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (401, 'AI', 'Anguilla', '安圭拉');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (404, 'GW', 'Guinea-Bissau', '几内亚比绍');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (407, 'BM', 'Bermuda 1', '百慕大群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (408, 'LC', 'Saint Lucia', '圣卢西亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (410, 'JE', 'Jersey', '泽西岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (411, 'GG', 'Guernsey', '格恩西岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (413, 'MG', 'Madeira Islands', '马德拉群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (414, 'PT', 'Azores', '亚速尔群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (415, 'es', 'Balearic Islands', '巴利阿里群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (419, 'MF', 'Saint Martin', '圣马丁');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (44, 'GH', 'Ghana', '加纳');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (45, 'CA', 'Canada', '加拿大');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (49, 'KH', 'Cambodia', '柬埔寨');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (5, 'GP', 'Guadeloupe', '瓜德罗普');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (50, 'GA', 'Gabon', '加蓬');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (52, 'DJ', 'Djibouti', '吉布提');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (53, 'CZ', 'Czech Rep.', '捷克');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (533, 'LS', 'The Kingdom of Lesot', '莱索托');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (56, 'ZW', 'Zimbabwe', '津巴布韦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (564, 'WF', 'Wallis et Futuna', '瓦利斯和富图纳群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (58, 'GN', 'Guinea', '几内亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (6, 'GU', 'Guam', '关岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (66, 'KY', 'Cayman Islands', '开曼群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (67, 'CM', 'Cameroon', '喀麦隆');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (69, 'QA', 'Qatar', '卡塔尔');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (70, 'HR', 'Croatia', '克罗地亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (71, 'KM', 'Union of Comoros', '科摩罗');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (715, 'MP', 'Northern Mariana Isl', '北马里亚纳群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (73, 'KE', 'Kenya', '肯尼亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (74, 'CI', 'Cotedivoire', '科特迪瓦');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (75, 'KW', 'Kuwait', '科威特');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (76, 'CK', 'Cook Islands', '库克群岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (8, 'CN', 'China', '中国');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (81, 'LA', 'Laos', '老挝');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (82, 'LV', 'Latvia', '拉脱维亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (823, 'ME', 'The Republic of Mont', '黑山');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (83, 'AG', 'Antigua', '安提瓜');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (87, 'LB', 'Lebanon', '黎巴嫩');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (88, 'LR', 'Liberia', '利比里亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (89, 'LY', 'Libya', '利比亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (92, 'AU', 'Australia', '澳大利亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (94, 'LT', 'Lithuania', '立陶宛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (95, 'RE', 'Reunion Island', '留尼汪岛');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (97, 'RO', 'Romania', '罗马尼亚');
INSERT INTO country (id, two_letter_code, name, chinese_name) VALUES (99, 'LU', 'Luxemburg ', '卢森堡');